#24 Fix email regex
bdragon300/mongoengine-migrate pull request #34
Opened 2020-12-14 21:50 UTC by vmdhhh

I think this should be enough for a normal email check.
Please let me know your thoughts.

2020-12-20 22:30 UTC, vmdhhh commented on mongoengine_migrate/fields/converters/common.py
> +        r"\A[^\W][A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z",
@bdragon300  I have made the suggested changes. Let me know if it's ok.

2020-12-22 18:57 UTC, bdragon300 commented on mongoengine_migrate/fields/converters/common.py
> +        r"\A[^\W][A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z",
@vmdhhh `A-Z` in domain name (after `@`) should also be changed to `\p{L}` to support IDN domains.

2020-12-22 18:58 UTC, bdragon300 requested changes

2020-12-22 18:58 UTC, bdragon300 commented on mongoengine_migrate/fields/converters/common.py
> +        email_regex = r"\A[^\W][A-Z0-9._%+-]+@[A-Z0-9.-]+\.\p{L}+\Z"
@vmdhhh A-Z in domain name (after @) should also be changed to \p{L} to support IDN domains.

2020-12-23 08:18 UTC, bdragon300 approved these changes
Looks good. Merged, thanks.

2020-12-23 08:18 UTC, merged